config/routes.rb
Rails.application.routes.draw do

    resources :footballers

end

app/models/footballer.rb
class Footballer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/footballers_controller.rb
class FootballersController < ApplicationController
  def index
    # binding.pry
    @footballers = Footballer.all
  end

  def show
    @footballer = Footballer.find(params[:id])
  end


  def new
    #instantiate an empty footballer object
    @footballer = Footballer.new
  end

  def create
    Footballer.create(footballer_params)
    redirect_to(footballers_path)
  end

  def edit
  @footballer = Footballer.find(params[:id])
  end

  def update
    #binding.pry
    #look up the planet in the planets database
    @footballer = Footballer.find(params[:id])
    #update the attributes
    @footballer.update(footballer_params)
    redirect_to(footballers_path)
  end

  def destroy
    #binding.pry
    #Look uyp the planet in the database using the id from params
    footballer = Footballer.find(params[:id]).destroy
    footballer.destroy
    #Delete planet from the database
    redirect_to(footballers_path)
  end

   private
  #this is a security methof that allows you to update the following columns in the database
  def footballer_params
    params.require(:footballer).permit(:first_name, :last_name, :team, :image, :nationality, :caps)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/footballers/edit.html.erb
<!-- YOU MUST USE AN EQUALS SIGN IN LUNE 2 OR IT WILL NOT WORK -->

<%= form_for @footballer do |f| %>

<%=f.label :first_name %>
<%=f.text_field :first_name %>

<%=f.label :last_name %>
<%=f.text_field :last_name %>

<%=f.label :caps %>
<%= f.text_field :caps %>

<%= f.label :team %>
<%= f.text_field :team %>

<%= f.label :nationality %>
<%= f.text_field :nationality %>

<%= f.label :image %>
<%= f.text_field :image %>

<%= f.submit 'EDIT FOOTBALLER'%>

<%end%>

app/views/footballers/index.html.erb
<div class="player-list">
<% @footballers.each do |footballer| %>
 <div class="list-group-item">
 <%= link_to footballer_path(footballer.id) do %>
 <%= image_tag(footballer.image, class: 'index-image')%>
 <%end%>
<ul class="footballer">
    <li><%=link_to(footballer.last_name,footballer_path(footballer.id))%></li>
     <li><%=link_to('EDIT', edit_footballer_path(footballer.id))%></li>
    <li><%=link_to('DELETE',footballer_path(footballer.id), method: :delete) %></li>

      </ul>
    </div>
  <%end%>
</div>

app/views/footballers/new.html.erb
<!-- YOU MUST USE AN EQUALS SIGN IN LUNE 2 OR IT WILL NOT WORK -->

<%= form_for @footballer do |f| %>

<%=f.label :first_name %>
<%=f.text_field :first_name %>

<%=f.label :last_name %>
<%=f.text_field :last_name %>

<%=f.label :caps %>
<%= f.text_field :caps %>

<%= f.label :team %>
<%= f.text_field :team %>

<%= f.label :nationality %>
<%= f.text_field :nationality %>

<%= f.label :image %>
<%= f.text_field :image %>

<%= f.submit 'CREATE FOOTBALLER'%>

<%end%>

app/views/footballers/show.html.erb
<div class="footballer-info">
<h3>  <%= @footballer.first_name%> <%=@footballer.last_name%> </h3>
<h4> <%= @footballer.team %> <%= @footballer.nationality %> <%= @footballer.caps %> </h4>
<%= image_tag(@footballer.image, width: 500)%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FootballApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:action]%>">
<h1>|| FOOTBALLERS ||</h1>
  <header>
    <nav>
    <li><%=link_to('Footballers', footballers_path)%></li>
    <li><%= link_to('New Footballer', new_footballer_path)%></li>
    </nav>
  </header>
<%= yield %>

</body>
</html>